#
#
#


# NAVER OPEN API
# 통합 검색어 트렌드, https://openapi.naver.com/v1/datalab/search
naveropenapi:
  datalab:
    search:
        application:
          application_url: https://openapi.naver.com/v1/datalab/search
          client_id: client_id
          client_secret: client_secret

